openapi: 3.0.0
info:
  title: SEC API Tool
  version: 1.0.0
paths:
  /query:
    get:
      summary: Proxy to sec-api query endpoint
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: SEC API response
